/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.31
 * Generated at: 2025-04-07 09:46:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class addMember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1743987920082L));
    _jspx_dependants.put("jar:file:/C:/eclipse/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/movie_review/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602841572000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/css/bootstrap.min.css\" />\r\n");
      out.write("<title>회원 가입</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function checkForm() {\r\n");
      out.write("		if (!document.newMember.m_id.value) {\r\n");
      out.write("			alert(\"아이디를 입력하세요.\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (!document.newMember.m_password.value) {\r\n");
      out.write("			alert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (document.newMember.m_password.value != document.newMember.m_password_confirm.value) {\r\n");
      out.write("			alert(\"비밀번호를 동일하게 입력하세요.\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	    if (!document.newMember.m_name.value) {\r\n");
      out.write("	        alert(\"성명을 입력하세요.\");\r\n");
      out.write("	        return false;\r\n");
      out.write("	    }\r\n");
      out.write("\r\n");
      out.write("	    if (!document.newMember.m_mail1.value) {\r\n");
      out.write("	        alert(\"이메일을 입력하세요.\");\r\n");
      out.write("	        return false;\r\n");
      out.write("	    }\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container py-4\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"p-5 mb-4 bg-body-tertiary rounded-3\">\r\n");
      out.write("			<div class=\"container-fluid py-3\">\r\n");
      out.write("				<h1 class=\"display-5 fw-bold\">회원 가입</h1>\r\n");
      out.write("				<p class=\"col-md-8 fs-4\">Membership Joining</p>      \r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("		<div class=\"row align-items-md-stretch text-center\">\r\n");
      out.write("			<form name=\"newMember\"  action=\"processAddMember.jsp\" method=\"post\" onsubmit=\"return checkForm()\">\r\n");
      out.write("				<div class=\"mb-3 row\">\r\n");
      out.write("					<label class=\"col-sm-2 \">아이디</label>\r\n");
      out.write("					<div class=\"col-sm-3\">\r\n");
      out.write("						<input name=\"m_id\" type=\"text\" class=\"form-control\" placeholder=\"id\" >\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mb-3 row\">\r\n");
      out.write("					<label class=\"col-sm-2\">비밀번호</label>\r\n");
      out.write("					<div class=\"col-sm-3\">\r\n");
      out.write("						<input name=\"m_password\" type=\"password\" class=\"form-control\" placeholder=\"password\" >\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mb-3 row\">\r\n");
      out.write("					<label class=\"col-sm-2\">비밀번호확인</label>\r\n");
      out.write("					<div class=\"col-sm-3\">\r\n");
      out.write("						<input name=\"m_password_confirm\" type=\"password\" class=\"form-control\" placeholder=\"password confirm\" >\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mb-3 row\">\r\n");
      out.write("					<label class=\"col-sm-2\">성명</label>\r\n");
      out.write("					<div class=\"col-sm-3\">\r\n");
      out.write("						<input name=\"m_name\" type=\"text\" class=\"form-control\" placeholder=\"name\" >\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			\r\n");
      out.write("				<div class=\"mb-3 row\">\r\n");
      out.write("					<label class=\"col-sm-2\">이메일</label>\r\n");
      out.write("					<div class=\"col-sm-10\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-sm-4\">\r\n");
      out.write("								<input type=\"text\" name=\"m_mail1\" maxlength=\"50\" class=\"form-control\"  placeholder=\"email\">\r\n");
      out.write("							</div> @\r\n");
      out.write("							<div class=\"col-sm-3\">\r\n");
      out.write("								<select name=\"mail2\" class=\"form-select\">\r\n");
      out.write("									<option>naver.com</option>\r\n");
      out.write("									<option>daum.net</option>\r\n");
      out.write("									<option>gmail.com</option>\r\n");
      out.write("									<option>nate.com</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>		\r\n");
      out.write("					</div>		\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"mb-3 row\">\r\n");
      out.write("					<div class=\"col-sm-offset-2 col-sm-10 \">\r\n");
      out.write("						<input type=\"submit\" class=\"btn btn-primary \" value=\"등록 \" > \r\n");
      out.write("						<input type=\"reset\" class=\"btn btn-primary \" value=\"취소 \" onclick=\"reset()\" >\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("	</div>	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
